POST http://localhost:8080/api/v1/auth/register-do
Host: localhost:8080
Cache-Control: no-cache
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="email"

qkfl4@naver.com
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="password"

1234
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="userName"

baek
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###
POST http://localhost:8080/api/v1/auth/login-do?username=qkfl4%40naver.com&password=1234
Content-Type: application/x-www-form-urlencoded

> {%
client.global.set("JSESSIONID", response.headers.valueOf("Set-Cookie").split(";")[0].split("=")[1]);
client.log("쿠키: "+client.global.get("JSESSIONID"));
%}

###
GET http://localhost:8080/api/v1/search/book?query=spring&page=1&size=10
Cookie: JSESSIONID={{JSESSIONID}}

###
GET http://localhost:8080/api/v1/search/book?query=spring&page=2&size=10
Cookie: JSESSIONID={{JSESSIONID}}

###
GET http://localhost:8080/api/v1/search/book?query=spring%20boot&page=1&size=10
Cookie: JSESSIONID={{JSESSIONID}}

###
GET http://localhost:8080/api/v1/history/my?page=1&size=10
Cookie: JSESSIONID={{JSESSIONID}}

###
GET http://localhost:8080/api/v1/history/top10
Cookie: JSESSIONID={{JSESSIONID}}

###